app = "jorbites-notifier"
primary_region = 'mad'

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"
WORKER_COUNT = "1"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = "256mb"
cpu_kind = "shared"
cpus = 1

[metrics]
port = 9091
path = "/metrics"
