name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Clone Wiki
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          cp -r docs/* wiki/
          cd wiki
          git add .
          git commit -m "Sync docs to wiki" || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git || echo "Push failed"
