name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Clone Wiki
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          cp -r docs/* wiki/
          cd wiki
          git add .
          git commit -m "Sync docs to wiki"
          git push
