name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Clone Wiki with Authentication
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Push changes to Wiki
        run: |
          cd wiki
          git add .
          git commit -m "Sync docs to wiki" || echo "No changes to commit"
          git push origin master
